# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_Files\AddPicture.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_pic(object):
    def setupUi(self, add_pic):
        add_pic.setObjectName("add_pic")
        add_pic.resize(431, 460)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI_Files\\facial-recognition.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        add_pic.setWindowIcon(icon)
        self.browseButton = QtWidgets.QPushButton(add_pic)
        self.browseButton.setGeometry(QtCore.QRect(350, 360, 75, 31))
        self.browseButton.setObjectName("browseButton")
        self.pictureLabel = QtWidgets.QLabel(add_pic)
        self.pictureLabel.setEnabled(True)
        self.pictureLabel.setGeometry(QtCore.QRect(10, 20, 411, 311))
        self.pictureLabel.setText("")
        self.pictureLabel.setScaledContents(False)
        self.pictureLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pictureLabel.setObjectName("pictureLabel")
        self.showDir = QtWidgets.QTextEdit(add_pic)
        self.showDir.setEnabled(True)
        self.showDir.setGeometry(QtCore.QRect(10, 360, 331, 31))
        self.showDir.setStatusTip("")
        self.showDir.setReadOnly(True)
        self.showDir.setObjectName("showDir")
        self.nameLabel = QtWidgets.QLineEdit(add_pic)
        self.nameLabel.setGeometry(QtCore.QRect(10, 410, 331, 31))
        self.nameLabel.setText("")
        self.nameLabel.setObjectName("nameLabel")
        self.addButton = QtWidgets.QPushButton(add_pic)
        self.addButton.setGeometry(QtCore.QRect(350, 410, 75, 31))
        self.addButton.setObjectName("addButton")

        self.retranslateUi(add_pic)
        QtCore.QMetaObject.connectSlotsByName(add_pic)

    def retranslateUi(self, add_pic):
        _translate = QtCore.QCoreApplication.translate
        add_pic.setWindowTitle(_translate("add_pic", "Add picture"))
        self.browseButton.setText(_translate("add_pic", "Browse"))
        self.showDir.setPlaceholderText(_translate("add_pic", "Browse to select your picture"))
        self.nameLabel.setPlaceholderText(_translate("add_pic", "Enter your name"))
        self.addButton.setText(_translate("add_pic", "AddPicture"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_pic = QtWidgets.QWidget()
    ui = Ui_add_pic()
    ui.setupUi(add_pic)
    add_pic.show()
    sys.exit(app.exec_())
